name: main
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  step-1:
    name: Step 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

  step-2:
    name: Build Infra and Deploy to ${{ matrix.environment == 'dev' && 'Development' || 'Staging' }} Environment - ${{ matrix.region == 'us-east-1' && 'Primary region' || 'Secondary region' }}
    runs-on: ubuntu-latest
    needs: step-1
    strategy:
      matrix:
        region: [ 'us-east-1', 'us-west-2' ]
        environment: [ 'dev', 'staging' ]
    env:
      AWS_ENVIRONMENT: ${{ matrix.environment }}
    if: ${{ github.env.AWS_ENVIRONMENT == 'dev' || github.env.AWS_ENVIRONMENT == 'staging'}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: echo
        run: echo ${{ github.env.AWS_ENVIRONMENT }}